// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "auth": clusters Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-auth/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ShowClustersPath computes a request path to the show action of clusters.
func ShowClustersPath() string {

	return fmt.Sprintf("/api/clusters/")
}

// Get clusters configuration
func (c *Client) ShowClusters(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowClustersRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowClustersRequest create the request corresponding to the show action endpoint of the clusters resource.
func (c *Client) NewShowClustersRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
