// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "auth": logout Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-auth/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-jenkins-idler/internal/auth
// --pkg=client
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// LogoutLogoutPath computes a request path to the logout action of logout.
func LogoutLogoutPath() string {

	return fmt.Sprintf("/api/logout")
}

// Logout user
func (c *Client) LogoutLogout(ctx context.Context, path string, redirect *string) (*http.Response, error) {
	req, err := c.NewLogoutLogoutRequest(ctx, path, redirect)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewLogoutLogoutRequest create the request corresponding to the logout action endpoint of the logout resource.
func (c *Client) NewLogoutLogoutRequest(ctx context.Context, path string, redirect *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if redirect != nil {
		values.Set("redirect", *redirect)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
