// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "auth": organization Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-auth/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-jenkins-idler/internal/auth
// --pkg=client
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateOrganizationPayload is the organization create action payload.
type CreateOrganizationPayload struct {
	// The name of the new organization
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// CreateOrganizationPath computes a request path to the create action of organization.
func CreateOrganizationPath() string {

	return fmt.Sprintf("/api/organizations")
}

// Create a new organization
func (c *Client) CreateOrganization(ctx context.Context, path string, payload *CreateOrganizationPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateOrganizationRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateOrganizationRequest create the request corresponding to the create action endpoint of the organization resource.
func (c *Client) NewCreateOrganizationRequest(ctx context.Context, path string, payload *CreateOrganizationPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ListOrganizationPath computes a request path to the list action of organization.
func ListOrganizationPath() string {

	return fmt.Sprintf("/api/organizations")
}

// Lists organizations that the user has access to
func (c *Client) ListOrganization(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListOrganizationRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListOrganizationRequest create the request corresponding to the list action endpoint of the organization resource.
func (c *Client) NewListOrganizationRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
