// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "auth": resource_roles Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-auth/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-jenkins-idler/internal/auth
// --pkg=client
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListAssignedResourceRolesPath computes a request path to the listAssigned action of resource_roles.
func ListAssignedResourceRolesPath(resourceID string) string {
	param0 := resourceID

	return fmt.Sprintf("/api/resources/%s/roles/assigned", param0)
}

// List assigned roles by resource
func (c *Client) ListAssignedResourceRoles(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListAssignedResourceRolesRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListAssignedResourceRolesRequest create the request corresponding to the listAssigned action endpoint of the resource_roles resource.
func (c *Client) NewListAssignedResourceRolesRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
