// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "auth": userinfo Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-auth/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ShowUserinfoPath computes a request path to the show action of userinfo.
func ShowUserinfoPath() string {

	return fmt.Sprintf("/api/userinfo")
}

// Get the authenticated user - part of the OAuth/OpenID connect authentication flow
func (c *Client) ShowUserinfo(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowUserinfoRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowUserinfoRequest create the request corresponding to the show action endpoint of the userinfo resource.
func (c *Client) NewShowUserinfoRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
