kind: Template
apiVersion: v1
metadata:
  name: jenkins-idler
labels:
  template: jenkins-idler
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: jenkins-idler
  spec:
    replicas: 1
    selector:
      service: jenkins-idler
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: jenkins-idler
      spec:
        containers:
        - env:
          - name: JC_IDLE_AFTER
            value: "45"
          - name: JC_IDLE_LONG_BUILD
            value: "3"
          - name: JC_CHECK_INTERVAL
            value: "15"
          - name: JC_MAX_RETRIES
            value: "10"
          - name: JC_MAX_RETRIES_QUIET_INTERVAL
            value: "30"
          - name: JC_JENKINS_PROXY_API_URL
            value: "http://jenkins-proxy:9091"
          - name: JC_F8TENANT_API_URL
            value: "http://f8tenant"
          - name: JC_TOGGLE_API_URL
            value: "http://f8toggles/api"
          - name: JC_LOG_LEVEL
            value: "info"
          - name: GODEBUG
            value: "gctrace=0"
          - name: JC_AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: core
                key: auth.serviceurl
          - name: JC_AUTH_TOKEN_KEY
            valueFrom:
              secretKeyRef:
                name: jenkins-idler
                key: auth.token.key
          - name: JC_SERVICE_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: jenkins-idler
                key: service.account.id
          - name: JC_SERVICE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: jenkins-idler
                key: service.account.secret
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: jenkins-idler
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /api/idler/cluster
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/idler/cluster
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "30m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: jenkins-idler
    name: jenkins-idler
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: jenkins-idler
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8-services-fabric8-jenkins-idler
  required: true
- name: IMAGE_TAG
  value: latest
  required: true
